version: '3'
services:
  reverse-proxy:
    image: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
  metabase:
    depends_on:
      - reverse-proxy
    image: metabase/metabase
    restart: always
    expose:
      - "3000"
