version: '3'
services:
  reverse-proxy:
    image: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/backend-not-found.html:/var/www/html/backend-not-found.html
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./conf/includes/proxy.conf:/etc/nginx/includes/proxy.conf
    networks:
      - metabase_site
networks:
  metabase_site:
    external:
      name: metabase_network
